// Full working Unsplash URLs + embedCode placeholders

export const featuredVideos = [
  {
    id: 'v1',
    title: 'What is life insurance and why do you need it?',
    seriesId: 'health-basics',
    duration: '3:24',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    tag: 'Basics',
    tagColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'v2',
    title: 'Term vs whole life — what\'s the real difference?',
    seriesId: 'choosing-plan',
    duration: '4:10',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    tag: 'Planning',
    tagColor: 'bg-purple-100 text-purple-700',
  },
  {
    id: 'v3',
    title: 'How the life insurance claim process works',
    seriesId: 'cashless-claims',
    duration: '3:55',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    tag: 'Claims',
    tagColor: 'bg-green-100 text-green-700',
  },
  {
    id: 'v4',
    title: 'How much life cover does your family actually need?',
    seriesId: 'health-basics',
    duration: '4:22',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
    tag: 'Must know',
    tagColor: 'bg-red/10 text-red',
  },
  {
    id: 'v5',
    title: 'What is a No-Claim Bonus & how to maximise it',
    seriesId: 'wellness-benefits',
    duration: '2:58',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=600&q=80',
    tag: 'Benefits',
    tagColor: 'bg-green-100 text-green-700',
  },
  {
    id: 'v6',
    title: 'Pre-existing conditions & waiting periods — know your rights',
    seriesId: 'health-basics',
    duration: '3:55',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    tag: 'Must know',
    tagColor: 'bg-red/10 text-red',
  },
  {
    id: 'v7',
    title: 'Critical illness cover — cancer, heart attack, stroke explained',
    seriesId: 'critical-illness',
    duration: '4:05',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    tag: 'Critical illness',
    tagColor: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'v8',
    title: 'How 80C & 10(10D) tax benefits work on life insurance',
    seriesId: 'tax-cover',
    duration: '3:30',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    tag: 'Tax & cover',
    tagColor: 'bg-blue-100 text-blue-700',
  },
  // Myth busted videos
  {
    id: 'm1',
    title: 'Do life insurance companies actually pay claims?',
    seriesId: 'myths',
    duration: '2:45',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    tag: 'Myth busted',
    tagColor: 'bg-red/10 text-red',
  },
  {
    id: 'm2',
    title: 'Is term insurance really a waste if you don\'t die?',
    seriesId: 'myths',
    duration: '3:10',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    tag: 'Myth busted',
    tagColor: 'bg-red/10 text-red',
  },
  {
    id: 'm3',
    title: 'Can I have more than one life insurance policy?',
    seriesId: 'myths',
    duration: '2:20',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    tag: 'FAQ',
    tagColor: 'bg-gray-100 text-gray-600',
  },
  {
    id: 'm4',
    title: 'What happens to my policy if I stop paying premiums?',
    seriesId: 'myths',
    duration: '3:05',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    tag: 'FAQ',
    tagColor: 'bg-gray-100 text-gray-600',
  },
]

export const videoSeries = [
  {
    id: 'health-basics',
    title: 'Life Insurance Basics',
    subtitle: 'What every Indian family needs to know',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    videos: 5,
    tag: 'Start Here',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'cashless-claims',
    title: 'How Claims Work',
    subtitle: 'Process, documents, timelines',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    videos: 4,
    tag: 'Claims',
    tagColor: 'bg-green-600 text-white',
  },
  {
    id: 'choosing-plan',
    title: 'Choosing the Right Plan',
    subtitle: 'Term, ULIP, whole life, endowment',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    videos: 4,
    tag: 'Planning',
    tagColor: 'bg-purple-600 text-white',
  },
  {
    id: 'critical-illness',
    title: 'Critical Illness Cover',
    subtitle: 'Cancer, heart attack, stroke and more',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    videos: 3,
    tag: 'Important',
    tagColor: 'bg-amber-500 text-white',
  },
  {
    id: 'wellness-benefits',
    title: 'Wellness & Benefits',
    subtitle: 'Riders, add-ons and what\'s worth it',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
    videos: 3,
    tag: 'Benefits',
    tagColor: 'bg-green-600 text-white',
  },
  {
    id: 'renewal-tips',
    title: 'Renewal & Portability',
    subtitle: 'Switch insurers without losing benefits',
    thumbnail: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=600&q=80',
    videos: 3,
    tag: 'Tips',
    tagColor: 'bg-blue-500 text-white',
  },
  {
    id: 'tax-cover',
    title: 'Tax & Life Insurance',
    subtitle: '80C, 10(10D), GST exemption',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    videos: 3,
    tag: 'Tax',
    tagColor: 'bg-blue-600 text-white',
  },
  {
    id: 'myths',
    title: 'Myths & FAQs',
    subtitle: 'Real questions, no sales pitch',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    videos: 4,
    tag: 'Myth busted',
    tagColor: 'bg-red text-white',
  },
]

export const policyVideos = [
  {
    id: 'policy-1',
    title: 'GST on life insurance removed — what it means for your premium',
    date: 'May 2025',
    duration: '4:30',
    embedCode: '',
    tag: 'Regulatory Update',
    tagColor: 'bg-red/10 text-red',
    summary: 'The GST exemption on life insurance premiums has been extended. Here\'s exactly how much you save and what it means for your policy.',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
  },
  {
    id: 'policy-2',
    title: 'IRDAI\'s new claim settlement rules — your rights explained',
    date: 'April 2025',
    duration: '5:00',
    embedCode: '',
    tag: 'Policy Change',
    tagColor: 'bg-amber-100 text-amber-700',
    summary: 'New IRDAI rules require claim settlement within 30 days. What this means for nominees and how to make sure your family is protected.',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
  },
  {
    id: 'policy-3',
    title: 'Budget 2026 — how the new 80C changes affect life insurance',
    date: 'Feb 2026',
    duration: '3:50',
    embedCode: '',
    tag: 'Budget Update',
    tagColor: 'bg-blue-100 text-blue-700',
    summary: 'The Union Budget revised Section 80C limits. Here\'s how the changes affect your life insurance premium deductions.',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
  },
  {
    id: 'policy-4',
    title: 'Insurance for All by 2047 — what the government\'s plan means for you',
    date: 'March 2025',
    duration: '4:15',
    embedCode: '',
    tag: 'Government Scheme',
    tagColor: 'bg-green-100 text-green-700',
    summary: 'The government\'s universal insurance programme — what it means for coverage, pricing, and access across India.',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
  },
  {
    id: 'policy-5',
    title: 'New IRDAI surrender value rules — what if you exit early?',
    date: 'January 2025',
    duration: '3:30',
    embedCode: '',
    tag: 'Regulatory Update',
    tagColor: 'bg-red/10 text-red',
    summary: 'IRDAI revised guaranteed surrender values for life insurance policies. Know what you\'re entitled to if you exit a policy early.',
    thumbnail: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=600&q=80',
  },
  {
    id: 'policy-6',
    title: 'Life insurance portability — switch without losing benefits',
    date: 'December 2024',
    duration: '4:00',
    embedCode: '',
    tag: 'Policy Change',
    tagColor: 'bg-amber-100 text-amber-700',
    summary: 'IRDAI portability rules protect your waiting period credits and benefits when you switch life insurers.',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
  },
]

export const categories = ['All', 'Basics', 'Claims', 'Planning', 'Critical illness', 'Benefits', 'Must know', 'Tax & cover', 'Myth busted']
