// ─────────────────────────────────────────────────────────────
// Health Insurance Video Platform — Content Data
// Thumbnails: Unsplash (reliable, no API key needed)
// embedCode: '' — paste your iframe embed code here when ready
// ─────────────────────────────────────────────────────────────

const unsplash = (id, params = 'w=600&q=80') =>
  `https://images.unsplash.com/photo-${id}?${params}`

export const featuredVideos = [
  {
    id: 'v1',
    title: 'What is Health Insurance & Why Do You Need It?',
    seriesId: 'health-basics',
    duration: '3:24',
    embedCode: '',
    thumbnail: unsplash('1576091160550-2173dba999ef'),
    tag: 'Basics',
    tagColor: 'bg-blue-100 text-blue-700',
    shareText: 'Watch this short video to understand why health insurance is essential for every family.',
  },
  {
    id: 'v2',
    title: 'How Cashless Hospitalisation Works — Step by Step',
    seriesId: 'cashless-claims',
    duration: '2:45',
    embedCode: '',
    thumbnail: unsplash('1559757148-5c350d0d3c56'),
    tag: 'Claims',
    tagColor: 'bg-green-100 text-green-700',
    shareText: 'Here\'s exactly how to use your cashless health insurance at a hospital.',
  },
  {
    id: 'v3',
    title: 'Family Floater vs Individual Health Plan — Which is Better?',
    seriesId: 'choosing-plan',
    duration: '3:45',
    embedCode: '',
    thumbnail: unsplash('1554224155-6726b3ff858f'),
    tag: 'Planning',
    tagColor: 'bg-purple-100 text-purple-700',
    shareText: 'Confused between family floater and individual health plans? This explains it simply.',
  },
  {
    id: 'v4',
    title: 'Critical Illness Insurance — What It Covers & Why You Need It',
    seriesId: 'critical-illness',
    duration: '4:22',
    embedCode: '',
    thumbnail: unsplash('1576091160399-112ba8d25d1d'),
    tag: 'Critical',
    tagColor: 'bg-amber-100 text-amber-700',
    shareText: 'Critical illness can wipe out savings. Watch this before it\'s too late.',
  },
  {
    id: 'v5',
    title: 'What is a No-Claim Bonus & How to Maximise It',
    seriesId: 'wellness-benefits',
    duration: '2:58',
    embedCode: '',
    thumbnail: unsplash('1568992688065-536aad8a12f6'),
    tag: 'Benefits',
    tagColor: 'bg-green-100 text-green-700',
    shareText: 'Stay healthy and get rewarded — here\'s how the No-Claim Bonus works.',
  },
  {
    id: 'v6',
    title: 'Pre-existing Diseases & Waiting Periods — Know Your Rights',
    seriesId: 'health-basics',
    duration: '3:55',
    embedCode: '',
    thumbnail: unsplash('1450101499163-c8848c66ca85'),
    tag: 'Must Know',
    tagColor: 'bg-red/10 text-red',
    shareText: 'If you have a pre-existing condition, watch this before buying health insurance.',
  },
]

export const videoSeries = [
  {
    id: 'health-basics',
    title: 'Health Insurance Basics',
    subtitle: 'What every Indian family needs to know',
    thumbnail: unsplash('1576091160550-2173dba999ef'),
    videos: 5,
    tag: 'Start Here',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'cashless-claims',
    title: 'Cashless Claims Explained',
    subtitle: 'How to use your policy when it matters most',
    thumbnail: unsplash('1559757148-5c350d0d3c56'),
    videos: 4,
    tag: 'Popular',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'choosing-plan',
    title: 'Choosing the Right Plan',
    subtitle: 'Individual vs family floater — which suits you?',
    thumbnail: unsplash('1554224155-6726b3ff858f'),
    videos: 3,
    tag: 'Must Watch',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'critical-illness',
    title: 'Critical Illness Cover',
    subtitle: 'Cancer, heart attack, stroke — are you covered?',
    thumbnail: unsplash('1576091160399-112ba8d25d1d'),
    videos: 3,
    tag: 'Important',
    tagColor: 'bg-amber-500 text-white',
  },
  {
    id: 'wellness-benefits',
    title: 'Wellness & Preventive Benefits',
    subtitle: 'Health check-ups, OPD, and wellness rewards',
    thumbnail: unsplash('1492725764893-90b379c2b6e7'),
    videos: 3,
    tag: 'Benefits',
    tagColor: 'bg-green-600 text-white',
  },
  {
    id: 'renewal-tips',
    title: 'Renewal & Portability',
    subtitle: 'Switch insurers without losing your benefits',
    thumbnail: unsplash('1450101499163-c8848c66ca85'),
    videos: 3,
    tag: 'Tips',
    tagColor: 'bg-blue-500 text-white',
  },
]

export const policyVideos = [
  {
    id: 'policy-1',
    title: 'IRDAI Bima Sugam — What It Means for Health Insurance Buyers',
    date: 'May 2025',
    duration: '4:30',
    embedCode: '',
    tag: 'Regulatory Update',
    tagColor: 'bg-red/10 text-red',
    summary: 'The new Bima Sugam marketplace simplifies health insurance purchase and portability for all buyers.',
    thumbnail: unsplash('1450101499163-c8848c66ca85'),
  },
  {
    id: 'policy-2',
    title: 'New Health Insurance Standardisation Norms — 20 Key Changes',
    date: 'April 2025',
    duration: '5:00',
    embedCode: '',
    tag: 'Policy Change',
    tagColor: 'bg-amber-100 text-amber-700',
    summary: 'IRDAI standardised over 20 health insurance terms. Here\'s what changed and how it benefits you.',
    thumbnail: unsplash('1576091160550-2173dba999ef'),
  },
  {
    id: 'policy-3',
    title: 'Mental Health Coverage is Now Mandatory — Your Rights Explained',
    date: 'March 2025',
    duration: '3:50',
    embedCode: '',
    tag: 'New Rule',
    tagColor: 'bg-blue-100 text-blue-700',
    summary: 'All health insurers must now cover mental illness treatment. Know what you\'re entitled to.',
    thumbnail: unsplash('1559757148-5c350d0d3c56'),
  },
  {
    id: 'policy-4',
    title: 'PED Waiting Period Rules Revised — Is Your Policy Better Now?',
    date: 'February 2025',
    duration: '4:15',
    embedCode: '',
    tag: 'Compliance',
    tagColor: 'bg-blue-100 text-blue-700',
    summary: 'IRDAI revised pre-existing disease waiting periods. Find out if your policy just got better.',
    thumbnail: unsplash('1554224155-6726b3ff858f'),
  },
  {
    id: 'policy-5',
    title: 'Cashless Anywhere — New IRDAI Circular Explained',
    date: 'January 2025',
    duration: '3:30',
    embedCode: '',
    tag: 'Regulatory Update',
    tagColor: 'bg-red/10 text-red',
    summary: 'Insurers must now offer cashless claims at any hospital within 1 hour.',
    thumbnail: unsplash('1568992688065-536aad8a12f6'),
  },
  {
    id: 'policy-6',
    title: 'Health Insurance Portability — Switch Without Losing Benefits',
    date: 'December 2024',
    duration: '4:00',
    embedCode: '',
    tag: 'Policy Change',
    tagColor: 'bg-amber-100 text-amber-700',
    summary: 'IRDAI portability rules protect your waiting period credits when you switch insurers.',
    thumbnail: unsplash('1492725764893-90b379c2b6e7'),
  },
]

export const categories = ['All', 'Basics', 'Claims', 'Planning', 'Critical', 'Benefits', 'Must Know']
