// ─────────────────────────────────────────────────────────────
// Health Insurance Video Platform — Content Data
// Replace embedCode with your actual iframe embed code
// ─────────────────────────────────────────────────────────────

export const videoSeries = [
  {
    id: 'health-basics',
    title: 'Health Insurance Basics',
    subtitle: 'What every Indian family needs to know',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    videos: 8,
    tag: 'Start Here',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'cashless-claims',
    title: 'Cashless Claims Made Simple',
    subtitle: 'How to use your policy when it matters most',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    videos: 6,
    tag: 'Popular',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'choosing-plan',
    title: 'Choosing the Right Plan',
    subtitle: 'Individual vs family floater — which is better?',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    videos: 5,
    tag: 'Must Watch',
    tagColor: 'bg-red text-white',
  },
  {
    id: 'critical-illness',
    title: 'Critical Illness Cover',
    subtitle: 'Cancer, heart attack, stroke — are you covered?',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    videos: 4,
    tag: 'Important',
    tagColor: 'bg-amber-500 text-white',
  },
  {
    id: 'maternity-cover',
    title: 'Maternity & Newborn Cover',
    subtitle: 'Planning for your family\'s health from day one',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
    videos: 4,
    tag: 'Family',
    tagColor: 'bg-pink-500 text-white',
  },
  {
    id: 'renewal-tips',
    title: 'Renewal & Portability Tips',
    subtitle: 'Switch insurers without losing your benefits',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    videos: 3,
    tag: 'Tips',
    tagColor: 'bg-blue-500 text-white',
  },
]

export const featuredVideos = [
  {
    id: 'v1',
    title: 'What is a Sum Insured? (And how much do you really need?)',
    seriesId: 'health-basics',
    duration: '3:24',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    tag: 'Basics',
    tagColor: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'v2',
    title: 'Cashless vs Reimbursement — Which is Better?',
    seriesId: 'cashless-claims',
    duration: '2:58',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
    tag: 'Claims',
    tagColor: 'bg-green-100 text-green-700',
  },
  {
    id: 'v3',
    title: 'Pre-existing Diseases — What Gets Covered & When',
    seriesId: 'health-basics',
    duration: '4:10',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    tag: 'Must Know',
    tagColor: 'bg-red/10 text-red',
  },
  {
    id: 'v4',
    title: 'Family Floater vs Individual Plan — Decoded',
    seriesId: 'choosing-plan',
    duration: '3:45',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    tag: 'Planning',
    tagColor: 'bg-purple-100 text-purple-700',
  },
  {
    id: 'v5',
    title: 'How to File a Claim Without Rejection',
    seriesId: 'cashless-claims',
    duration: '5:12',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    tag: 'Claims',
    tagColor: 'bg-green-100 text-green-700',
  },
  {
    id: 'v6',
    title: 'Critical Illness vs Health Insurance — Know the Difference',
    seriesId: 'critical-illness',
    duration: '3:33',
    embedCode: '',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
    tag: 'Critical',
    tagColor: 'bg-amber-100 text-amber-700',
  },
]

// Short 9:16 reels — offers/rewards (insurance discounts, not course offers)
export const rewardReels = [
  {
    id: 'r1',
    title: 'Get 10% Discount on First Year Premium',
    tag: 'Offer',
    tagColor: 'bg-red text-white',
    duration: '0:30',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    subtitle: 'For new health policy buyers',
  },
  {
    id: 'r2',
    title: 'No-Claim Bonus — Up to 50% Sum Insured Boost',
    tag: 'Reward',
    tagColor: 'bg-green-600 text-white',
    duration: '0:45',
    thumbnail: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=600&q=80',
    subtitle: 'Stay healthy, get rewarded',
  },
  {
    id: 'r3',
    title: 'Family Floater — Add 2 Members Free',
    tag: 'Bundle',
    tagColor: 'bg-blue-600 text-white',
    duration: '0:40',
    thumbnail: 'https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?w=600&q=80',
    subtitle: 'Limited period offer',
  },
  {
    id: 'r4',
    title: 'Annual Health Check-up Included — Zero Extra Cost',
    tag: 'Benefit',
    tagColor: 'bg-purple-600 text-white',
    duration: '0:35',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    subtitle: 'Free with all plans',
  },
]

// Policy briefings — keep as is
export const policyVideos = [
  {
    id: 'policy-1',
    title: 'IRDAI Bima Sugam — What It Means for Health Insurance Buyers',
    date: 'May 2025',
    duration: '4:30',
    embedCode: '',
    tag: 'Regulatory Update',
    tagColor: 'bg-red/10 text-red',
    summary: 'The new Bima Sugam marketplace simplifies health insurance purchase and portability.',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
  },
  {
    id: 'policy-2',
    title: 'New Health Insurance Standardisation — Key Changes Explained',
    date: 'April 2025',
    duration: '5:00',
    embedCode: '',
    tag: 'Policy Change',
    tagColor: 'bg-amber-100 text-amber-700',
    summary: 'IRDAI standardised 20+ health insurance terms. Here\'s what changed and how it helps you.',
    thumbnail: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
  },
  {
    id: 'policy-3',
    title: 'Mental Health Coverage is Now Mandatory — Your Rights',
    date: 'March 2025',
    duration: '3:50',
    embedCode: '',
    tag: 'New Rule',
    tagColor: 'bg-blue-100 text-blue-700',
    summary: 'All health insurers must now cover mental illness treatment. Know what you\'re entitled to.',
    thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80',
  },
  {
    id: 'policy-4',
    title: 'Waiting Period Rules Have Changed — Important Update',
    date: 'February 2025',
    duration: '4:15',
    embedCode: '',
    tag: 'Compliance',
    tagColor: 'bg-blue-100 text-blue-700',
    summary: 'IRDAI revised PED waiting periods. Find out if your policy is now better than before.',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
  },
]

export const categories = ['All', 'Basics', 'Claims', 'Planning', 'Critical Illness', 'Family', 'Renewal']
